#include "funcs.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define SoluNum 8
#define RemaindersNum 5
#define SeqLen 10

int main(void){
	int (*CongEquaSolus[SoluNum])(int k) = {CongruenceEquationSolu1,
				CongruenceEquationSolu2,
				CongruenceEquationSolu3,
				CongruenceEquationSolu4,
				CongruenceEquationSolu5,
				CongruenceEquationSolu6,
				CongruenceEquationSolu7,
				CongruenceEquationSolu8};
	int remaindersOfCongEqus[RemaindersNum] = {-1, 2, -2, 3, -3};
	
	// Firstly, generate sequence A which is a hyperincremental integer array
	int SeqA[SeqLen] = {0};
	int SeqB[SeqLen] = {0};
	int RandowQ;
	GenHyperIncrementalSeq(SeqA, SeqLen);
	// The only require to RandowQ is that it must be bigger than the summary
	// of the total elements in SeqA
	// So I simplely add 10 to the sum of SeqA and use the result as RandowQ's
	// value.
	RandowQ = SumOfSeq(SeqA, SeqLen)+10;
	// The critial B sequence is generated by calling following function
	GenPackageSeq(SeqA, SeqLen, RandowQ, SeqB);

	// Secondly, another important task is to generate a special 0-1 string
	// Generate a random integer number K as a initial seed.
	srand(time(NULL));
	int RandowK = rand()%100000;
	int i = 0;	
	int p;		// p will store a prime number
	int zeroOneStr[RemaindersNum*2] = {0};
	for (; i<SoluNum; i++){
		p = CongEquaSolus[i](RandowK);
		// To simplify the progress, I use the first found prime number
		// as the need one (but another python project is created to test
		// all the available prime numbers to find out whether they can 
		// lead the final comparison to a perpetual false.
		if (IsPrime(p))		
			break;
	}
	// In this step we will get an important 0-1 string
	GenZeroOneString(remaindersOfCongEqus, RemaindersNum, p, zeroOneStr);

	// Thirdly, use sequence B and 0-1 string to calculate two summaries and
	// compare one with the other. The comparison result is the final result
	// we need.
	int C = 0;		// C will store a summary calculated from seq B
	int D = 0;		// D will store a summary calculated from B and 0-1 string
	C = CalcLeftCmpEle(SeqB, SeqLen);
	D = CalcRightCmpEle(SeqB, SeqLen, zeroOneStr);
	if (C > D)
		printf("false result!\n");
	else
		printf("true result!\n");

	return 0;
}
